@extends('layout')
@section('title', $row->name.' — Review '.($draft['workflowMode']==='finalize' ? 'finalization' : $mode))
@section('content')
@if($draft['workflowMode']==='finalize')<p class="warning">Finalization is irreversible. Confirm posts distribution and moves all leftovers directly once. This event cannot reopen.</p>@elseif($mode==='correction')<p class="warning">Confirm changes the flagged report and adds an immutable correction log. It does not move stock, change Unit Cost or rewrite original history.</p>@else<p>Review moves no stock. Confirm posts these actual supplies once.</p>@endif
@php($review=$draft['review'])
@if(isset($review['supplies']))<p>Actual movement date: {{ isset($review['actual_date']) ? \App\Support\DisplayDates::businessDate($review['actual_date']) : 'Unknown' }}</p><x-app.table-region label="Reviewed supplies" class="table-wrap"><table><thead><tr><th>Item</th><th>Source</th><th>Units</th></tr></thead><tbody>@foreach($review['supplies'] as $supply)@php($item=$items->firstWhere('id',$supply['item_id']))<tr><th>{{ $item?->name }}<small class="app-item-sku">{{ $item?->sku }}</small></th><td>{{ $supply['source']==='external' ? 'External / unknown origin' : ($destinations[$supply['source']] ?? $supply['source']) }}</td><td>{{ number_format($supply['quantity']) }}</td></tr>@endforeach</tbody></table></x-app.table-region>@endif
@if(isset($review['lines']))<x-app.table-region label="Finalization counts and destinations" class="table-wrap"><table><thead><tr><th>Item</th><th>Brought</th><th>Remaining</th><th>Distributed (including loss)</th><th>Destinations</th></tr></thead><tbody>@foreach($review['lines'] as $itemId=>$line)@php($item=$items->firstWhere('id',(int)$itemId))<tr><th>{{ $item?->name }}<small class="app-item-sku">{{ $item?->sku }}</small></th><td>{{ number_format($line['brought']) }}</td><td>{{ number_format($line['remaining']) }}</td><td>{{ number_format($line['brought']-$line['remaining']) }}</td><td>@foreach($line['allocations'] as $key=>$quantity)<p>{{ $destinations[$key] ?? $key }}: {{ number_format($quantity) }}</p>@endforeach</td></tr>@endforeach</tbody></table></x-app.table-region>@endif
@if(isset($review['report']))<x-app.table-region label="Report-only changes" class="table-wrap"><table><thead><tr><th>Item</th><th>Brought before → after</th><th>Remaining before → after</th><th>Distributed before → after</th></tr></thead><tbody>@foreach($review['report'] as $item=>$line)@php($before=$review['before'][$item])<tr><th>{{ $line['item'] }}<small class="app-item-sku">{{ $line['sku'] }}</small></th><td>{{ number_format($before['brought']) }} → {{ number_format($line['brought']) }}</td><td>{{ number_format($before['remaining']) }} → {{ number_format($line['remaining']) }}</td><td>{{ number_format($before['distributed']) }} → {{ number_format($line['distributed']) }}</td></tr>@endforeach</tbody></table></x-app.table-region>@if($review['explanation'])<p>{{ $review['explanation'] }}</p>@endif @endif
<div class="actions"><a class="discard" href="/events/{{ $row->id }}">Discard changes</a><a href="{{ $base }}?work={{ $token }}">Keep editing</a><form method="post" action="{{ $base }}/confirm/{{ $token }}">@csrf<input type="hidden" name="_deliberate" value="1"><button class="primary" data-confirm="{{ $draft['workflowMode']==='finalize' ? 'Finalize this event once? This cannot be undone or reopened.' : 'Confirm these reviewed changes?' }}">{{ $draft['workflowMode']==='finalize' ? 'Finalize event irreversibly' : 'Confirm '.$mode }}</button></form></div>
<script src="/requests.js" defer></script>
@endsection
