@extends('design.phase-a.layout')
@section('title', 'General elements')
@section('intro', 'The small set of shared components behind inventory screens. Specimens are static; controls have no workflow handlers.')
@section('content')
<nav aria-label="On this page" class="guide-index">
    <a href="#foundation">Foundations</a><a href="#headers">Headers & navigation</a><a href="#actions">Actions & status</a><a href="#fields">Fields & validation</a><a href="#data">Tables & records</a><a href="#feedback">Notices & dialogs</a>
</nav>
<section id="foundation" class="guide-section" aria-labelledby="foundation-title">
    <div class="section-intro"><p class="eyebrow">01 / Foundation</p><h2 id="foundation-title">Readable, quiet and consistent</h2><p>Proposal: generous page structure, compact data rows, neutral surfaces and one purple action color. This is a fresh theme, not a reproduction of the rough mockups.</p></div>
    <div class="grid gap-6 lg:grid-cols-2">
        <div class="specimen space-y-4"><h3>Typography</h3><p class="text-3xl font-semibold tracking-tight">Page heading</p><p class="text-xl font-semibold">Section heading</p><p>Body text stays at 16px with comfortable line spacing. Labels use the same readable scale; secondary metadata is 14px.</p><p class="text-sm text-base-content/70">Recorded October 6, 2026 · Jasmine Davidson</p><p class="tabular-nums text-right">2,550 units · $0.125 per unit</p></div>
        <div class="specimen space-y-4"><h3>Palette and surfaces</h3><div class="grid grid-cols-2 gap-3"><div class="swatch bg-primary text-primary-content">Primary<br><code>#5b21b6</code></div><div class="swatch bg-base-200">Page<br><code>#f5f5f7</code></div><div class="swatch border border-base-300 bg-base-100">Panel<br><code>#ffffff</code></div><div class="swatch bg-base-content text-base-100">Text<br><code>#20212b</code></div></div><p class="text-sm">Use semantic color names. Success, warning and error always have text as well as color.</p></div>
    </div>
    <div class="specimen mt-5"><h3>Spacing and density</h3><p class="mt-2">4px base rhythm: 8px between related controls, 16px between fields, 24px panel padding, 32px between sections. Buttons and fields are at least 40px tall. Table rows use 12px vertical padding. At narrow widths, fields stack; wide data scrolls within its own region.</p><div class="mt-4 flex flex-wrap items-end gap-4"><span class="rounded bg-primary/15 p-2">8px</span><span class="rounded bg-primary/15 p-4">16px</span><span class="rounded bg-primary/15 p-6">24px</span><span class="rounded bg-primary/15 p-8">32px</span></div></div>
    <p class="guide-note">Implementation vocabulary: <code>bg-base-100</code>, <code>text-base-content</code>, <code>gap-4</code>, <code>tabular-nums</code>. Shared descriptive classes organize guide sections, specimens and action rows.</p>
</section>
<section id="headers" class="guide-section" aria-labelledby="headers-title">
    <div class="section-intro"><p class="eyebrow">02 / Structure</p><h2 id="headers-title">Headers and navigation</h2><p>Show the route back, the record title and its state, then a short explanation. Navigation goes somewhere; buttons perform an action.</p></div>
    <div class="specimen space-y-4">
        <nav class="breadcrumbs text-sm" aria-label="Example breadcrumb"><ul><li><a href="/design/phase-a/examples#requests">Requests example</a></li><li aria-current="page">Convention ribbon restock</li></ul></nav>
        <div class="flex flex-wrap items-center gap-3"><h3 class="text-2xl font-semibold">Convention ribbon restock</h3><span class="badge badge-warning badge-lg">Draft</span></div>
        <p>Supplies requested for Indianapolis IN.</p>
        <nav class="flex flex-wrap gap-2" aria-label="Example local sections"><a class="btn btn-sm btn-primary" aria-current="location" href="#headers">Overview</a><a class="btn btn-sm btn-ghost" href="#data">Recorded activity</a></nav>
    </div>
    <p class="guide-note">Title badges remain subordinate to the heading. Current navigation is identified by <code>aria-current</code>; links stay recognizable and keyboard focus is visible. Long titles and action rows wrap.</p>
</section>
<section id="actions" class="guide-section" aria-labelledby="actions-title">
    <div class="section-intro"><p class="eyebrow">03 / Action language</p><h2 id="actions-title">Buttons, links and status</h2><p>A primary action is visually clear; alternatives are quieter. Use explicit workflow verbs where effects differ.</p></div>
    <div class="grid gap-6 lg:grid-cols-2">
        <div class="specimen space-y-4"><h3>Action hierarchy</h3><div class="flex flex-wrap gap-3"><button type="button" class="btn btn-primary">Save</button><button type="button" class="btn btn-outline">Edit</button><button type="button" class="btn btn-ghost">Show filters</button><button type="button" class="btn btn-error btn-outline">Discard changes</button></div><div class="flex flex-wrap gap-3"><button type="button" class="btn btn-primary" disabled>Save unavailable</button><button type="button" class="btn btn-primary"><span class="loading loading-spinner loading-xs" aria-hidden="true"></span>Saving…</button><button type="button" class="btn btn-sm btn-outline">Remove line</button></div><p><a class="link link-primary" href="/design/phase-a/examples#item">View item example</a></p><p class="text-sm">Illustrative controls only. Loading is a displayed state, not a running operation.</p></div>
        <div class="specimen space-y-4"><h3>Status vocabulary</h3><div class="flex flex-wrap gap-2"><span class="badge badge-warning">Draft</span><span class="badge badge-warning">Request</span><span class="badge badge-warning">Requested</span><span class="badge badge-success">Active</span><span class="badge badge-success">Ordered</span><span class="badge badge-success">Shipped</span><span class="badge badge-success">Receiving</span><span class="badge badge-primary">Received</span><span class="badge badge-primary">Finalized</span><span class="badge badge-primary">Complete</span><span class="badge badge-outline">Inactive</span><span class="badge badge-outline">Archived</span><span class="badge badge-outline">View only</span></div><div class="rounded-lg border border-base-300 p-4"><p class="font-medium">Cancelled: two design candidates</p><div class="mt-3 flex flex-wrap gap-3"><span class="badge badge-error">Cancelled</span><span class="badge badge-outline">Cancelled</span></div><p class="mt-3 text-sm">Presentation is unresolved; neither candidate is selected here.</p></div></div>
    </div>
    <div class="specimen mt-5"><h3>Action rows</h3><p class="mt-2">Primary last, right aligned. Actions stay near their affected section. Ordinary Cancel styling remains a decision: the first row follows current red guidance; the second proposes a neutral alternative.</p><div class="action-row mt-4"><button type="button" class="btn btn-error btn-outline">Cancel</button><button type="button" class="btn btn-primary">Review request</button></div><div class="action-row mt-4 border-t border-base-300 pt-4"><button type="button" class="btn btn-outline">Cancel — alternative</button><button type="button" class="btn btn-primary">Review request</button></div></div>
    <p class="guide-note"><code>btn btn-primary</code>, <code>btn btn-outline</code>, <code>badge badge-warning</code>. Static buttons have <code>type="button"</code>; no handlers or submission. In the working product, unavailable actions need an understandable reason.</p>
</section>
<section id="fields" class="guide-section" aria-labelledby="fields-title">
    <div class="section-intro"><p class="eyebrow">04 / Input</p><h2 id="fields-title">Fields, choices and validation</h2><p>Permanent labels above inputs. Optional values are named explicitly; helper text explains units and expectations. Blank and zero are separate examples.</p></div>
    <div class="specimen"><div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        <label class="field"><span>Request title</span><input class="input w-full" value="Convention ribbon restock"><span class="field-help">A short name that identifies the request.</span></label>
        <label class="field"><span>Storage location</span><select class="select w-full"><option>Central</option><option>Ames IA</option><option>Boston MA</option><option>Indianapolis IN</option><option>Milwaukee WI</option></select></label>
        <label class="field"><span>Recorded date</span><input class="input w-full" type="date" value="2026-10-06"></label>
        <label class="field"><span>Counted units — blank</span><input class="input w-full" inputmode="numeric" aria-describedby="blank-help"><span id="blank-help" class="field-help">No count entered yet.</span></label>
        <label class="field"><span>Counted units — zero</span><input class="input w-full" inputmode="numeric" value="0" aria-describedby="zero-help"><span id="zero-help" class="field-help">An explicit count of no units.</span></label>
        <label class="field"><span>Unit cost (USD)</span><input class="input w-full text-right tabular-nums" value="0.125" readonly><span class="field-help">Read-only example; precision follows the workflow specification.</span></label>
        <label class="field"><span>Search inventory</span><input class="input w-full" type="search" placeholder="Category, collection or item name"></label>
        <label class="field"><span>Unavailable field</span><input class="input w-full" value="Central" disabled><span class="field-help">Disabled state specimen.</span></label>
        <label class="field"><span>Quantity — error state</span><input class="input input-error w-full" value="two" aria-invalid="true" aria-describedby="quantity-error"><span id="quantity-error" class="field-error">Enter a whole quantity, such as 200.</span></label>
        <label class="field md:col-span-2"><span>Rationale (optional)</span><textarea class="textarea w-full" rows="3">Count checked before packing for Gen Con.</textarea><span class="field-help">Optional explanation; corrections stay easy.</span></label>
    </div></div>
    <div class="grid gap-6 lg:grid-cols-2 mt-5"><fieldset class="specimen"><legend class="px-2 font-semibold">Collections — independent choices</legend><div class="space-y-3"><label class="choice"><input class="checkbox checkbox-primary" type="checkbox" checked> Ribbon · Pronoun</label><label class="choice"><input class="checkbox checkbox-primary" type="checkbox"> Enamel Pin · Tabletop Gaymers</label><label class="choice"><input class="checkbox checkbox-primary" type="checkbox" disabled> Unavailable choice</label></div></fieldset><fieldset class="specimen"><legend class="px-2 font-semibold">Illustrative presentation — one choice</legend><div class="space-y-3"><label class="choice"><input class="radio radio-primary" type="radio" name="density" checked> Comfortable</label><label class="choice"><input class="radio radio-primary" type="radio" name="density"> Compact</label></div></fieldset></div>
    <div class="specimen mt-5 border-error"><h3>Validation summary specimen</h3><p class="mt-2">Check the highlighted quantity before continuing.</p><a class="link link-primary" href="#quantity-error">Quantity: enter a whole number.</a></div>
    <p class="guide-note"><code>input</code>, <code>select</code>, <code>textarea</code>, <code>checkbox</code>, <code>radio</code>. Errors need text, <code>aria-invalid</code> and associated descriptions. A real submission should focus its error summary; this guide has no validation code.</p>
</section>
<section id="data" class="guide-section" aria-labelledby="data-title">
    <div class="section-intro"><p class="eyebrow">05 / Information</p><h2 id="data-title">Tables, metadata and notes</h2><p>Keep names left aligned, numeric values right aligned and values associated with their headings. Wide tables scroll within a labeled keyboard-accessible region.</p></div>
    <div class="specimen"><div class="table-region" role="region" tabindex="0" aria-label="Grouped inventory specimen"><table class="table"><caption>Individual units · illustrative balances</caption><thead><tr><th scope="col">Item</th><th scope="col" class="number">Central</th><th scope="col" class="number">Ames IA</th><th scope="col">State</th></tr></thead><tbody><tr class="table-group"><th colspan="4" scope="rowgroup">Ribbon · Pronoun</th></tr><tr><th scope="row">They/Them</th><td class="number">2,550</td><td class="number">120</td><td><span class="badge badge-success">Active</span></td></tr><tr><th scope="row">Any/All</th><td class="number">0</td><td class="number">80</td><td><span class="badge badge-success">Active</span></td></tr><tr class="table-group"><th colspan="4" scope="rowgroup">Enamel Pin · Tabletop Gaymers</th></tr><tr><th scope="row">Pride Dragon</th><td class="number">240</td><td class="number">—</td><td><span class="badge badge-outline">View only</span></td></tr></tbody></table></div><p class="mt-3 text-sm">Zero is a measured value. “—” means unavailable in this specimen; each workflow defines its own display semantics.</p></div>
    <div class="grid gap-6 lg:grid-cols-2 mt-5"><div class="specimen"><h3>Record metadata</h3><dl class="record-grid mt-4"><div><dt>Changed by</dt><dd>Jasmine Davidson</dd></div><div><dt>Recorded</dt><dd>Oct 6, 2026, 9:20 AM</dd></div><div><dt>Location</dt><dd>Milwaukee WI</dd></div></dl></div><div class="specimen"><h3>Permanent note presentation</h3><article class="mt-4 border-l-2 border-primary pl-4"><p>Set aside ribbons for the convention kit.</p><p class="mt-2 text-sm text-base-content/70">Wanda Lambert · Oct 6, 2026</p></article><p class="mt-3 text-sm">Notes keep their author and date. A correction is another entry, not an edit to history.</p></div></div>
    <div class="grid gap-6 lg:grid-cols-2 mt-5"><div class="specimen"><h3>No matching results</h3><p class="mt-2">No items match these filters.</p><p class="text-sm text-base-content/70">Try a broader collection or another location.</p><button type="button" class="btn btn-outline btn-sm mt-4">Clear filters</button></div><div class="specimen"><h3>Loading results</h3><div class="mt-4 flex items-center gap-3"><span class="loading loading-spinner" aria-hidden="true"></span><span>Loading inventory…</span></div><p class="mt-3 text-sm">Displayed state only. The product should retain useful context while loading and announce the resulting state.</p></div></div>
</section>
<section id="feedback" class="guide-section" aria-labelledby="feedback-title">
    <div class="section-intro"><p class="eyebrow">06 / Feedback</p><h2 id="feedback-title">Notices and dialog presentation</h2><p>Place feedback near the action or affected content. Describe the outcome and next useful step. Dialog examples below are inline visual specimens, not live modals.</p></div>
    <div class="space-y-3"><div class="alert alert-success"><strong>Saved.</strong><span>The changes have been recorded.</span></div><div class="alert alert-warning"><strong>Review the quantities.</strong><span>These displayed balances are illustrative.</span></div><div class="alert alert-error"><strong>Unable to save.</strong><span>Your entries remain available. Try again.</span></div><div class="alert alert-info"><strong>View only.</strong><span>This record can be read but not edited.</span></div></div>
    <div class="grid gap-6 lg:grid-cols-2 mt-5"><div class="specimen bg-base-200 p-6"><div class="dialog-specimen"><h3>Discard these changes?</h3><p class="mt-3">The unsaved quantities will be lost. The saved record remains unchanged.</p><div class="action-row mt-6"><button type="button" class="btn btn-outline">Keep editing</button><button type="button" class="btn btn-error">Discard changes</button></div></div></div><div class="specimen bg-base-200 p-6"><div class="dialog-specimen"><h3>Edit request title</h3><label class="field mt-4"><span>Title</span><input class="input w-full" value="Convention ribbon restock"></label><div class="action-row mt-6"><button type="button" class="btn btn-error btn-outline">Cancel</button><button type="button" class="btn btn-primary">Save</button></div></div></div></div>
    <p class="guide-note">Real modal implementation must name the dialog, place focus inside it, contain keyboard focus, let Escape dismiss safely and restore trigger focus. Live errors use an alert announcement; success uses a polite status announcement. These static examples intentionally create neither modal behavior nor live announcements.</p>
</section>
@endsection
