@extends('design.phase-a.layout')
@section('title', 'Example uses')
@section('intro', 'Shared components composed into realistic screens. All records and quantities are illustrative, with no calculations, persistence or workflow actions.')
@section('content')
<nav class="guide-index" aria-label="On this page"><a href="#search">Search & results</a><a href="#item">Item & history</a><a href="#requests">Request edit & review</a><a href="#counts">Counts & print</a><a href="#supporting">Catalog, people & events</a><a href="#wrapper">Application wrapper</a></nav>
<section id="search" class="guide-section" aria-labelledby="search-title">
    <div class="section-intro"><p class="eyebrow">01 / Browse</p><h2 id="search-title">Search and grouped inventory results</h2><p>Clear criteria above the results; collections and locations have separate labeled groups. Each checkbox gets its own line. Data density belongs in the table, not in the form.</p></div>
    <div class="specimen space-y-6">
        <h3 class="text-2xl">Inventory</h3>
        <label class="field max-w-2xl"><span>Search inventory</span><input class="input w-full" type="search" value="Ribbon"><span class="field-help">Category, collection or item name</span></label>
        <div class="grid gap-6 md:grid-cols-3"><fieldset><legend class="mb-3 font-semibold">Collections</legend><div class="space-y-3"><label class="choice"><input type="checkbox" class="checkbox checkbox-primary" checked> Ribbon · Pronoun</label><label class="choice"><input type="checkbox" class="checkbox checkbox-primary"> Ribbon · Tabletop Gaymers</label></div></fieldset><fieldset><legend class="mb-3 font-semibold">Storage locations</legend><div class="space-y-3"><label class="choice"><input type="checkbox" class="checkbox checkbox-primary" checked> Central</label><label class="choice"><input type="checkbox" class="checkbox checkbox-primary" checked> Ames IA</label><label class="choice"><input type="checkbox" class="checkbox checkbox-primary"> Milwaukee WI</label></div></fieldset><fieldset><legend class="mb-3 font-semibold">Events and incoming inventory</legend><div class="space-y-3"><label class="choice"><input type="checkbox" class="checkbox checkbox-primary"> Gen Con</label><label class="choice"><input type="checkbox" class="checkbox checkbox-primary"> In Transit</label><label class="choice"><input type="checkbox" class="checkbox checkbox-primary"> Ordered</label></div></fieldset></div>
        <div class="action-row"><button type="button" class="btn btn-ghost">Clear filters</button><button type="button" class="btn btn-outline">Show all</button><button type="button" class="btn btn-primary">Search</button></div>
        <div class="border-t border-base-300 pt-6"><div class="flex flex-wrap items-center justify-between gap-3"><h3>2 matching items</h3><span class="text-sm">Individual units · static results</span></div><div class="table-region mt-4" role="region" aria-label="Illustrative search results" tabindex="0"><table class="table"><caption class="sr-only">Ribbons at selected locations</caption><thead><tr><th scope="col">Item</th><th scope="col" class="number">Central</th><th scope="col" class="number">Ames IA</th></tr></thead><tbody><tr class="table-group"><th colspan="3" scope="rowgroup">Ribbon · Pronoun</th></tr><tr><th scope="row"><a class="link link-primary" href="#item">They/Them</a></th><td class="number">2,550</td><td class="number">120</td></tr><tr><th scope="row">Any/All</th><td class="number">0</td><td class="number">80</td></tr></tbody></table></div><div class="action-row mt-4"><button type="button" class="btn btn-outline btn-sm">Download CSV</button></div></div>
    </div>
    <p class="guide-note">The Search control has no handler. Changing a checkbox does not alter these specimen results. Working search behavior and visibility follow approved requirements; no policy is inferred from these examples.</p>
</section>
<section id="item" class="guide-section" aria-labelledby="item-title">
    <div class="section-intro"><p class="eyebrow">02 / Record</p><h2 id="item-title">Item details and recorded activity</h2><p>Separate current balances from descriptive details, then give history a full-width area. Values and notes remain readable without edit controls crowding every line.</p></div>
    <div class="specimen space-y-6">
        <a class="link link-primary text-sm" href="#search">← Inventory example</a><div class="flex flex-wrap items-center gap-3"><h3 class="text-2xl">They/Them ribbon</h3><span class="badge badge-success badge-lg">Active</span></div>
        <div class="grid gap-6 lg:grid-cols-3"><div class="rounded-lg border border-base-300 p-5"><h4 class="font-semibold">Current inventory</h4><dl class="mt-4 space-y-3"><div class="flex justify-between gap-4"><dt>Central</dt><dd class="tabular-nums font-medium">2,550</dd></div><div class="flex justify-between gap-4"><dt>Ames IA</dt><dd class="tabular-nums">120</dd></div><div class="flex justify-between gap-4"><dt>Milwaukee WI</dt><dd class="tabular-nums">180</dd></div><div class="flex justify-between gap-4"><dt>Gen Con</dt><dd class="tabular-nums">300</dd></div><div class="flex justify-between gap-4"><dt>In Transit</dt><dd class="tabular-nums">200</dd></div><div class="flex justify-between gap-4"><dt>Ordered</dt><dd class="tabular-nums">1,500</dd></div></dl><button class="btn btn-outline btn-sm mt-5" type="button">Edit inventory</button></div><div class="lg:col-span-2 rounded-lg border border-base-300 p-5"><div class="flex flex-wrap items-center justify-between gap-3"><h4 class="font-semibold">Item details</h4><button type="button" class="btn btn-outline btn-sm">Edit details</button></div><dl class="record-grid mt-5"><div><dt>Category</dt><dd>Ribbon</dd></div><div><dt>Collection</dt><dd>Pronoun</dd></div><div><dt>Illustrative SKU</dt><dd>R-P-THEY</dd></div><div><dt>Unit cost</dt><dd class="tabular-nums">$0.125</dd></div><div><dt>Count unit</dt><dd>Individual ribbon</dd></div></dl><h4 class="mt-6 font-semibold">Notes</h4><p class="mt-2">Pronoun ribbons for convention kits and community events. Store in packs of 100; count individual ribbons.</p></div></div>
        <div><div class="flex flex-wrap items-center justify-between gap-3"><h4 class="text-xl font-semibold">History</h4><span class="badge badge-outline">Read-only · newest first</span></div><div class="table-region mt-4" role="region" tabindex="0" aria-label="Illustrative item history"><table class="table"><thead><tr><th scope="col">Recorded / by</th><th scope="col">Activity</th><th scope="col" class="number">Quantity</th><th scope="col" class="number">Unit cost</th></tr></thead><tbody><tr><td><time datetime="2026-10-06">Oct 6, 2026</time><br><span class="text-sm">Wanda Lambert</span></td><td><strong>Inventory correction · Central</strong><p class="text-sm mt-1">Count verified before packing.</p></td><td class="number">−5</td><td class="number">$0.125</td></tr><tr><td><time datetime="2026-10-05">Oct 5, 2026</time><br><span class="text-sm">Jarod Nash</span></td><td>Relocation · Central → Ames IA</td><td class="number">±120</td><td class="number">$0.125</td></tr></tbody></table></div></div>
    </div>
    <p class="guide-note">Names, balances, SKU, cost and activity are invented sample compositions. Nothing reads the real item ledger. Preserve immutable history and workflow-specific precision when integrating any design.</p>
</section>
<section id="requests" class="guide-section" aria-labelledby="requests-title">
    <div class="section-intro"><p class="eyebrow">03 / Workflow presentation</p><h2 id="requests-title">Request editing and review</h2><p>Keep editing, review and outcome visually distinct. The review specimen summarizes entered values and effects without executing them.</p></div>
    <div class="specimen space-y-6"><div class="flex flex-wrap items-center gap-3"><h3 class="text-2xl">Convention ribbon restock</h3><span class="badge badge-warning">Draft</span></div><div class="grid gap-5 md:grid-cols-2"><label class="field md:col-span-2"><span>Title</span><input class="input w-full" value="Convention ribbon restock"></label><label class="field"><span>Source</span><select class="select w-full"><option>Central</option></select></label><label class="field"><span>Destination</span><select class="select w-full"><option>Indianapolis IN</option></select></label><label class="field md:col-span-2"><span>Request notes (optional)</span><textarea class="textarea w-full" rows="2">For the Gen Con convention kit.</textarea></label></div><h4 class="font-semibold">Requested items</h4><div class="table-region" role="region" tabindex="0" aria-label="Illustrative request editing"><table class="table"><thead><tr><th scope="col">Item</th><th scope="col" class="number">Source balance</th><th scope="col" class="number">Requested units</th><th scope="col">Line action</th></tr></thead><tbody><tr class="table-group"><th colspan="4" scope="rowgroup">Ribbon · Pronoun</th></tr><tr><th scope="row">They/Them</th><td class="number">2,550</td><td><input class="input input-sm w-28 text-right tabular-nums" value="200" inputmode="numeric" aria-label="Requested They/Them units"></td><td><button type="button" class="btn btn-sm btn-ghost">Remove</button></td></tr></tbody></table></div><div class="action-row"><button type="button" class="btn btn-error btn-outline">Cancel</button><button type="button" class="btn btn-outline">Save draft</button><button type="button" class="btn btn-primary">Review request</button></div></div>
    <div class="specimen mt-6 space-y-5"><div class="flex flex-wrap items-center gap-3"><h3 class="text-2xl">Review request</h3><span class="badge badge-warning">Draft</span></div><dl class="record-grid"><div><dt>Owner</dt><dd>Trinity Reese</dd></div><div><dt>Source</dt><dd>Central</dd></div><div><dt>Destination</dt><dd>Indianapolis IN</dd></div></dl><div class="table-region" role="region" tabindex="0" aria-label="Illustrative request review"><table class="table"><thead><tr><th scope="col">Item</th><th scope="col" class="number">Requested units</th></tr></thead><tbody><tr><th scope="row">They/Them ribbon</th><td class="number">200</td></tr></tbody></table></div><p>For the Gen Con convention kit.</p><div class="alert alert-info"><span>Review specimen only. No request is submitted and no inventory moves.</span></div><div class="action-row"><button type="button" class="btn btn-outline">Edit draft</button><button type="button" class="btn btn-primary">Submit request</button></div></div>
    <div class="specimen mt-6"><h3>Purchase pricing variant</h3><p class="mt-2 text-sm">Show currency units in the heading, preserve numeric alignment and give the total a clear boundary. Costs below are fixed examples, not calculated.</p><div class="grid gap-4 md:grid-cols-3 mt-4"><label class="field"><span>Manufacturer</span><input class="input w-full" value="Illustrative Print Co."></label><label class="field"><span>Shipping (USD)</span><input class="input w-full text-right" value="12.00"></label><label class="field"><span>Shipping allocation</span><select class="select w-full"><option>By line total</option><option>By quantity</option></select></label></div><div class="table-region mt-5" role="region" tabindex="0" aria-label="Static purchase pricing"><table class="table"><thead><tr><th scope="col">Item</th><th scope="col" class="number">Units</th><th scope="col" class="number">Merchandise</th><th scope="col" class="number">Shipping</th><th scope="col" class="number">Order cost</th><th scope="col" class="number">Cost / unit</th></tr></thead><tbody><tr><th scope="row">They/Them ribbon</th><td class="number">1,000</td><td class="number">$125.00</td><td class="number">$12.00</td><td class="number">$137.00</td><td class="number">$0.137</td></tr></tbody></table></div><div class="mt-5 flex justify-end border-t border-base-300 pt-4"><p class="text-lg font-semibold">Illustrative order total <span class="ml-4 tabular-nums">$137.00</span></p></div></div>
</section>
<section id="counts" class="guide-section" aria-labelledby="counts-title">
    <div class="section-intro"><p class="eyebrow">04 / Physical work</p><h2 id="counts-title">Count entry and printable information</h2><p>Count inputs stay close to item names. Review emphasizes differences. The paper specimen favors handwriting space and legible monochrome rules.</p></div>
    <div class="specimen"><div class="flex flex-wrap items-center justify-between gap-3"><h3>Count entry · Central</h3><span class="badge badge-warning">In progress</span></div><div class="table-region mt-5" role="region" tabindex="0" aria-label="Illustrative count entry"><table class="table"><thead><tr><th scope="col">Item</th><th scope="col" class="number">Recorded units</th><th scope="col" class="number">Counted units</th></tr></thead><tbody><tr><th scope="row">They/Them ribbon</th><td class="number">2,550</td><td><input class="input w-28 text-right tabular-nums" value="2545" inputmode="numeric" aria-label="Counted They/Them units"></td></tr><tr><th scope="row">Any/All ribbon</th><td class="number">0</td><td><input class="input w-28 text-right tabular-nums" value="0" inputmode="numeric" aria-label="Counted Any/All units"></td></tr><tr><th scope="row">Pride Dragon pin</th><td class="number">240</td><td><input class="input w-28 text-right tabular-nums" inputmode="numeric" aria-label="Counted Pride Dragon units" aria-describedby="uncounted"></td></tr></tbody></table></div><p id="uncounted" class="mt-3 text-sm">Blank means no count entered; zero is an explicit count. No totals update in this guide.</p><div class="action-row mt-5"><button type="button" class="btn btn-outline">Save progress</button><button type="button" class="btn btn-primary">Review counts</button></div></div>
    <div class="specimen mt-6"><h3>Correction review specimen</h3><div class="table-region mt-4" role="region" tabindex="0" aria-label="Static correction review"><table class="table"><thead><tr><th scope="col">Item</th><th scope="col" class="number">Before</th><th scope="col" class="number">Counted</th><th scope="col" class="number">Change</th></tr></thead><tbody><tr><th scope="row">They/Them ribbon</th><td class="number">2,550</td><td class="number">2,545</td><td class="number font-semibold">−5</td></tr></tbody></table></div><div class="alert alert-warning mt-4"><span>Review the location and quantity before saving corrections. This is a static visual example.</span></div><div class="action-row mt-5"><button type="button" class="btn btn-outline">Edit counts</button><button type="button" class="btn btn-primary">Save corrections</button></div></div>
    <article class="paper-specimen mt-6" aria-labelledby="worksheet-title"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm">TG Inventory · Count worksheet</p><h3 id="worksheet-title" class="mt-2 text-2xl font-semibold">Central</h3></div><p class="text-sm">Illustrative worksheet<br>Individual units</p></div><div class="grid gap-4 sm:grid-cols-2 mt-6"><p>Counted by: <span class="writing-line"></span></p><p>Date: <span class="writing-line"></span></p></div><div class="table-region mt-6" role="region" tabindex="0" aria-label="Paper count worksheet specimen"><table class="table worksheet-table"><thead><tr><th scope="col">Item</th><th scope="col">SKU (illustrative)</th><th scope="col">Counted units</th></tr></thead><tbody><tr class="table-group"><th colspan="3" scope="rowgroup">Ribbon · Pronoun</th></tr><tr><th scope="row">They/Them</th><td>R-P-THEY</td><td class="write-cell"></td></tr><tr><th scope="row">Any/All</th><td>R-P-ANY</td><td class="write-cell"></td></tr><tr class="table-group"><th colspan="3" scope="rowgroup">Enamel Pin · Tabletop Gaymers</th></tr><tr><th scope="row">Pride Dragon</th><td>E-T-DRAGON</td><td class="write-cell"></td></tr></tbody></table></div><p class="mt-5 text-sm">Count individual units. Leave room for handwritten corrections.</p></article>
    <p class="guide-note">Paper is a white content surface even on screen. Print CSS removes surrounding guide chrome and prints this worksheet alone on this page. Use the browser's ordinary print command; no automatic print or print-button code. Physical printing is not verified.</p>
</section>
<section id="supporting" class="guide-section" aria-labelledby="supporting-title">
    <div class="section-intro"><p class="eyebrow">05 / Shared variants</p><h2 id="supporting-title">Catalog, people and event examples</h2><p>The same components also cover the supporting mockup screens. These variants demonstrate coverage without inventing permissions or implementing workflows.</p></div>
    <div class="specimen"><div class="flex flex-wrap items-center justify-between gap-3"><h3>Catalog · Collections</h3><button type="button" class="btn btn-primary btn-sm">Create collection</button></div><div class="table-region mt-4" role="region" tabindex="0" aria-label="Catalog collection specimen"><table class="table"><thead><tr><th scope="col">Collection</th><th scope="col">Category</th><th scope="col" class="number">Items</th><th scope="col">Status</th></tr></thead><tbody><tr><th scope="row">Pronoun</th><td>Ribbon</td><td class="number">4</td><td><span class="badge badge-success">Active</span></td></tr><tr><th scope="row">Queer Coven</th><td>Enamel Pin</td><td class="number">3</td><td><span class="badge badge-success">Active</span></td></tr></tbody></table></div></div>
    <div class="specimen mt-6"><h3>User directory specimen</h3><div class="table-region mt-4" role="region" tabindex="0" aria-label="Illustrative people and roles"><table class="table"><thead><tr><th scope="col">Name</th><th scope="col">Illustrative roles</th><th scope="col">Action</th></tr></thead><tbody><tr><th scope="row">Jarod Nash</th><td><div class="flex flex-wrap gap-2"><span class="badge badge-outline">Admin</span><span class="badge badge-outline">Manager</span></div></td><td><button type="button" class="btn btn-sm btn-outline">Edit roles</button></td></tr><tr><th scope="row">Jasmine Davidson</th><td><span class="badge badge-outline">Manager</span></td><td><button type="button" class="btn btn-sm btn-outline">Edit roles</button></td></tr></tbody></table></div><p class="mt-3 text-sm">Approved fictional sample associations, not real-account grants.</p><div class="grid gap-4 md:grid-cols-2 mt-5"><label class="field"><span>Display name</span><input class="input w-full" value="Jasmine Davidson"></label><label class="field"><span>Identity email — read only</span><input class="input w-full" value="jasmine@example.org" readonly><span class="field-help">Generated sample address.</span></label></div></div>
    <div class="specimen mt-6"><div class="flex flex-wrap items-center gap-3"><h3>Gen Con · Distribution summary</h3><span class="badge badge-primary">Finalized</span><span class="badge badge-outline">Corrected report</span></div><div class="table-region mt-4" role="region" tabindex="0" aria-label="Static event distribution summary"><table class="table"><thead><tr><th scope="col">Item</th><th scope="col" class="number">Brought</th><th scope="col" class="number">Remaining</th><th scope="col" class="number">Distributed</th></tr></thead><tbody><tr><th scope="row">They/Them ribbon</th><td class="number">300</td><td class="number">80</td><td class="number">220</td></tr></tbody></table></div><p class="mt-4">Report presentation is separate from original inventory posting. The static numbers do not authorize a report or inventory correction.</p><div class="mt-5 border-t border-base-300 pt-4"><h4 class="font-semibold">Leftover destination summary</h4><div class="flex flex-wrap gap-3 mt-3"><span class="badge badge-outline">Central · 50</span><span class="badge badge-outline">Indianapolis IN · 30</span></div></div></div>
</section>
<section id="wrapper" class="guide-section" aria-labelledby="wrapper-title">
    <div class="section-intro"><p class="eyebrow">06 / Application frame</p><h2 id="wrapper-title">Proposed application wrapper</h2><p>The wrapper gives people a stable place to navigate, identify their account and understand their current location. It surrounds the working page without competing with it.</p></div>
    <div class="overflow-hidden rounded-xl border border-base-300 bg-base-200">
        <header class="border-b border-base-300 bg-base-100 p-5">
            <div class="flex flex-wrap items-center justify-between gap-4">
                <div><p class="text-xl font-semibold tracking-tight">TG Inventory</p><p class="text-sm text-base-content/70">Tabletop Gaymers</p></div>
                <div class="flex flex-wrap items-center gap-3"><span class="badge badge-outline">Development preview</span><button type="button" class="btn btn-outline btn-sm" aria-label="Account menu specimen for Jasmine Davidson">JD · Jasmine Davidson ▾</button></div>
            </div>
        </header>
        <div class="grid lg:grid-cols-[13rem_minmax(0,1fr)]">
            <aside class="border-b border-base-300 bg-base-100 p-5 lg:border-b-0 lg:border-r" aria-label="Primary navigation specimen">
                <p class="mb-3 text-xs font-semibold uppercase tracking-widest text-base-content/70">Workspace</p>
                <nav class="flex flex-wrap gap-2 lg:flex-col" aria-label="Example primary navigation">
                    <button type="button" class="btn btn-primary justify-start">Inventory</button>
                    <button type="button" class="btn btn-ghost justify-start">Catalog</button>
                    <button type="button" class="btn btn-ghost justify-start">Purchases</button>
                    <button type="button" class="btn btn-ghost justify-start">Relocations</button>
                    <button type="button" class="btn btn-ghost justify-start">Events</button>
                    <button type="button" class="btn btn-ghost justify-start">Users</button>
                </nav>
                <p class="mt-5 text-sm text-base-content/70">Proposed primary navigation. The working app must show only authorized destinations.</p>
            </aside>
            <div class="min-w-0 p-5 sm:p-6">
                <div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_16rem]">
                    <div class="min-w-0 space-y-5">
                        <nav class="breadcrumbs text-sm" aria-label="Example location breadcrumb"><ul><li>Inventory</li><li aria-current="page">Browse</li></ul></nav>
                        <div><h3 class="text-2xl font-semibold">Inventory</h3><p class="mt-2 text-base-content/75">Find supplies by collection or storage location.</p></div>
                        <nav class="flex flex-wrap gap-2 border-b border-base-300 pb-4" aria-label="Example inventory section navigation"><button type="button" class="btn btn-primary btn-sm">Browse</button><button type="button" class="btn btn-ghost btn-sm">Location counts</button></nav>
                        <div class="rounded-lg border border-dashed border-base-300 bg-base-100 p-6 sm:p-8">
                            <p class="eyebrow">Main working area</p><h4 class="mt-3 text-xl font-semibold">Page-specific content lives here</h4><p class="mt-3">Search fields, inventory tables, request editors and record details use the shared component patterns. The surrounding shell stays consistent.</p>
                            <div class="mt-6 rounded-lg bg-base-200 p-5"><p class="text-sm text-base-content/70">Illustrative page section</p><p class="mt-2 font-medium">Ribbon · Pronoun</p><p class="mt-1 text-sm">They/Them · Central · 2,550 units</p></div>
                        </div>
                    </div>
                    <div class="rounded-lg border border-base-300 bg-base-100 p-4 shadow-sm" aria-label="Account dropdown open-state specimen">
                        <p class="text-xs font-semibold uppercase tracking-widest text-base-content/70">Account menu · open specimen</p>
                        <p class="mt-3 font-semibold">Jasmine Davidson</p><p class="text-sm text-base-content/70">Illustrative signed-in account</p>
                        <div class="mt-4 flex flex-col gap-2 border-t border-base-300 pt-3"><button type="button" class="btn btn-ghost justify-start">My profile</button><button type="button" class="btn btn-ghost justify-start">Sign out</button></div>
                        <p class="mt-3 text-sm text-base-content/70">Displayed beside the page to show its contents. In the product it would overlay beneath the account trigger, not reserve a page column.</p>
                    </div>
                </div>
                <footer class="mt-6 border-t border-base-300 pt-4 text-sm text-base-content/70">TG Inventory · Development environment</footer>
            </div>
        </div>
    </div>
    <div class="specimen"><h3>Navigation levels and narrow screens</h3><ul class="mt-3 list-disc space-y-2 pl-5"><li><strong>Application header:</strong> brand/home destination, environment context and account actions.</li><li><strong>Primary navigation:</strong> stable workflow areas; selected area has a distinct state.</li><li><strong>Section navigation:</strong> nearby tasks inside the selected area, such as Browse and Location counts.</li><li><strong>Breadcrumb:</strong> the current record's hierarchy when it provides a useful route back; avoid repeating every level unnecessarily.</li><li><strong>Working area:</strong> page title, local actions and content. Account actions stay in the shell.</li><li><strong>Narrow layout:</strong> primary navigation wraps above the page rather than relying on an unimplemented hidden menu. A future account popover should fit the viewport and support keyboard opening, Escape dismissal and focus return.</li></ul></div>
    <p class="guide-note">Static proposal only. Menu controls and navigation specimens are inert buttons, not working destinations; Sign out cannot end a session. The account panel is a visible open-state specimen, not a live dropdown. Permission filtering, responsive menu behavior and authentication remain existing application responsibilities.</p>
</section>

@endsection

