@extends('design.phase-a.layout')
@section('title', 'A fresh style guide')
@section('intro', 'Reusable elements and practical examples for clear, comfortable inventory work.')
@section('content')
<div class="max-w-3xl space-y-3"><p>The functional mockups identify the components we need. Their original styling is a rough draft, not the visual baseline. This guide develops a fresh presentation using Tailwind + daisyUI (Td).</p><p class="text-sm text-base-content/75">The guide is static: no simulated permissions, workflow calculations, saved records or submission code. Ordinary links navigate the guide and native fields illustrate their appearance.</p></div>
<div class="grid gap-6 lg:grid-cols-2">
<section class="specimen space-y-5" aria-labelledby="general-title"><p class="eyebrow">Component reference</p><h2 id="general-title">General elements</h2><p>The shared vocabulary for typography, layout and controls.</p><ul class="list-disc space-y-2 pl-5"><li>Typography, surfaces, spacing and page headers</li><li>Buttons, links, navigation and status badges</li><li>Fields, choices, help text and validation states</li><li>Tables, record details, notices and dialog presentation</li></ul><a class="btn btn-primary" href="/design/phase-a/elements">Explore general elements →</a></section>
<section class="specimen space-y-5" aria-labelledby="examples-title"><p class="eyebrow">Patterns in context</p><h2 id="examples-title">Example uses</h2><p>Realistic compositions made from the same shared components.</p><ul class="list-disc space-y-2 pl-5"><li>Search and grouped inventory results</li><li>Item details and recorded activity</li><li>Request editing and review summaries</li><li>Count entry and printable information</li><li>Catalog, user directory and event variants</li></ul><a class="btn btn-primary" href="/design/phase-a/examples">Explore example uses →</a></section>
</div>
<section class="specimen space-y-4" aria-labelledby="progress-title"><h2 id="progress-title">Visible progress</h2><ol class="list-decimal space-y-3 pl-5"><li><strong>Guide entry point</strong> — complete; this address stays stable.</li><li><strong>General elements</strong> — complete draft component reference.</li><li><strong>Example uses</strong> — complete draft static compositions.</li><li><strong>Refinement</strong> — complete draft; desktop, narrow-screen, keyboard and print-media checks passed.</li></ol><p class="text-sm text-base-content/75">Content completion is separate from your acceptance of the design. Nothing here adopts Td across the working app.</p></section>
<section class="specimen space-y-4" aria-labelledby="choices-title"><h2 id="choices-title">Design proposals for review</h2><p>A neutral page background, white surfaces, readable system typography and a deep purple primary action. Data stays compact; form controls have room to breathe. These are proposed defaults for discussion.</p><p>Two choices remain visible in the component page: ordinary Cancel styling and the Cancelled badge. Current guidance and alternatives are labeled separately.</p><p class="text-sm">Built with Tailwind 4.3.3 and daisyUI 5.7.47. No paid templates or MCP service used.</p></section>
@endsection

