@extends('layout')
@section('title', 'Review '.$mode.' — '.($row->title ?: 'Untitled request'))
@section('content')
<p>Reviewing {{ $kind }} #{{ $row->id }}. No stock has moved.</p>
@if($kind==='purchase')
<p>Supplier: {{ $suppliers->firstWhere('id',$review['supplier_id'])?->name }} · Receiving storage: {{ $locations->firstWhere('id',$review['receiving_location_id'])?->name }}</p>
<p>Ordered {{ \App\Support\DisplayDates::businessDate($review['ordered_date']) }} · Shipped {{ !empty($review['shipped_date']) ? \App\Support\DisplayDates::businessDate($review['shipped_date']) : '—' }} · Received {{ !empty($review['received_date']) ? \App\Support\DisplayDates::businessDate($review['received_date']) : '—' }} · Shipping: {{ $review['shipping_method']==='quantity' ? 'By quantity' : 'By line total' }}</p>
<x-app.table-region label="Acquisition cost breakdown" class="table-wrap"><table><thead><tr><th>Item</th><th>Units</th><th>Cost</th><th>Fee</th><th>Other Fees</th><th>Discount</th><th>Tax</th><th>Shipping</th><th>Acquisition</th><th>Acquisition/unit</th></tr></thead><tbody>
@foreach($review['lines'] as $itemId=>$line)<tr><th>{{ $items->firstWhere('id',(int)$itemId)?->name ?: '#'.$itemId }}</th><td>{{ number_format($line['quantity']) }}</td>@foreach(['cost','fee','other','discount','tax','shipping','acquisition'] as $field)<td>${{ \App\Support\PurchaseCosting::dollars($line[$field]) }}</td>@endforeach<td>${{ $line['acquisition_unit'] }}</td></tr>@endforeach
</tbody><tfoot><tr><th colspan="8">Total invoice (USD)</th><td colspan="2">${{ \App\Support\PurchaseCosting::dollars($review['total']) }}</td></tr></tfoot></table></x-app.table-region>
@if($mode==='receipt')<p>Receipt clears this purchase’s saved Ordered expectation and adds only these actual units. Catalog averages use current held storage, active events and In Transit under the confirmation lock; Ordered is excluded. Projections may change before confirmation.</p><x-app.table-region label="Receipt stock and cost preview" class="table-wrap"><table><thead><tr><th>Item</th><th>Held now → after</th><th>Catalog cost now → after</th></tr></thead><tbody>@foreach($review['projection'] as $itemId=>$projection)<tr><th>{{ $items->firstWhere('id',(int)$itemId)?->name }}</th><td>{{ number_format($projection['held']) }} → {{ number_format($projection['after_held']) }}</td><td>{{ \App\Support\StockNumbers::displayCost($projection['before_cost']) }} → {{ \App\Support\StockNumbers::displayCost($projection['after_cost']) }}</td></tr>@endforeach</tbody></table></x-app.table-region>@else<p>Confirmation changes only Ordered expectations. Held stock and catalog cost stay unchanged.</p>@endif
@else
<p>{{ $mode==='shipment' ? 'Shipped' : 'Received' }} date: {{ \App\Support\DisplayDates::businessDate($review['date']) }}</p><x-app.table-region label="Relocation posting review" class="table-wrap"><table><thead><tr><th>Item</th><th>Sent</th>@if($mode==='receipt')<th>Received</th><th>Stock effect</th>@endif</tr></thead><tbody>
@foreach($review['lines'] as $itemId=>$line)<tr><th>{{ $items->firstWhere('id',(int)$itemId)?->name ?: '#'.$itemId }}</th><td>{{ number_format((int)$line['sent']) }}</td>@if($mode==='receipt')@php($difference=(int)($line['received']??0)-(int)$line['sent'])<td>{{ number_format((int)($line['received']??0)) }}</td><td>@if($difference<0){{ number_format(-$difference) }} missing: remove this remainder from In Transit through a linked shortage adjustment.@elseif($difference>0){{ number_format($difference) }} extra: add this quantity at destination through a linked overage adjustment.@elseMatching transfer; held stock preserved.@endif</td>@endif</tr>@endforeach
</tbody></table></x-app.table-region>
@if($mode==='shipment')<p>Confirmation transfers actual sent units from {{ $locations->firstWhere('id',$row->source_location_id)?->name }} to In Transit. Requested quantities reserve nothing. Held quantity and Unit Cost stay unchanged.</p>@else<p>Confirmation clears all sent units from this request’s In Transit contribution and adds the actual received units at {{ $locations->firstWhere('id',$row->destination_location_id)?->name }}. Unit Cost stays unchanged.</p>@if($review['discrepancy'])<p class="warning">Permanent discrepancy: total held stock changes by received minus sent. This requires a Manager or Admin. Confirm only when this is the final outcome; otherwise go back and Save counts while awaiting more boxes.</p>@endif<p>{{ $review['explanation'] ?: 'No explanation entered.' }}</p>@endif
@endif
<form method="post" action="{{ $base }}/fulfillment/{{ $mode }}/confirm/{{ $token }}" class="actions">@csrf<input type="hidden" name="_deliberate" value="1"><a href="{{ $base }}/fulfillment/{{ $mode }}?work={{ $token }}">Back to details</a><a class="discard" href="{{ $base }}">Cancel {{ $mode }}</a>
@if($kind!=='relocation' || $mode!=='receipt' || !$review['discrepancy'] || \App\Support\RequestValues::manages(auth()->user(),'manager'))<button class="primary">{{ $mode==='order' ? 'Confirm order' : ($mode==='shipment' ? 'Confirm shipment' : ($kind==='purchase' ? 'Confirm receipt' : 'Complete receiving')) }}</button>@endif</form>
@endsection
