@extends('layout')
@section('title', $row->title)
@section('title-status')<span class="status-badge request-status {{ strtolower($row->status) }}">{{ $row->status }}</span>@endsection
@section('content')
<p>Relocation #{{ $row->id }} · Owner: {{ trim($owner->first_name.' '.$owner->last_name) ?: 'Account '.$owner->id }}</p>
<div class="actions"><a href="/relocations">All relocation requests</a><a class="button" href="/relocations/{{ $row->id }}/worksheet" target="_blank" rel="noopener">Packing worksheet</a>@if($editable)<a class="button" href="/relocations/{{ $row->id }}/edit">{{ $row->status==='Draft' ? 'Edit Draft' : 'Edit request' }}</a>@endif</div>
<p>{{ $locations->firstWhere('id',$row->source_location_id)?->name ?: 'Source not selected' }} → {{ $locations->firstWhere('id',$row->destination_location_id)?->name ?: 'Destination not selected' }}</p><p class="plain-text">{{ $row->details }}</p>
@if($manager || (int)$row->owner_id === (int)auth()->id())<details><summary>Edit title</summary><form method="post" action="/relocations/{{ $row->id }}/title" data-request-form>@csrf<input type="hidden" name="_deliberate" value="1"><input type="hidden" name="revision" value="{{ old('revision',$row->revision) }}"><label>Title<input name="title" maxlength="255" value="{{ old('title',$row->title) }}" required></label><button>Save title</button></form></details>@endif
<h2>Requested Items</h2><p>Projections use current inventory. Saved fulfillment is preparation only; no shipment has been recorded.</p>
<form method="post" action="/relocations/{{ $row->id }}/fulfillment" data-request-form>@csrf<input type="hidden" name="_deliberate" value="1"><input type="hidden" name="revision" value="{{ old('revision',$row->revision) }}"><x-app.table-region label="Requested items and fulfillment" class="table-wrap"><table class="stock-editor"><thead><tr><th>Item</th><th>Source: current → projected</th><th>Destination: current → projected</th><th>Requested</th><th>Fulfillment preparation (optional)</th></tr></thead><tbody>@include('requests.relocation-rows',['quantities'=>$lines->map(fn($line)=>$line->quantity)->all(),'fulfillment'=>true,'columns'=>5])</tbody></table></x-app.table-region>@if($manager && $row->status==='Requested')<div class="actions"><button>Save fulfillment preparation</button></div>@endif</form>
<form method="post" action="/relocations/{{ $row->id }}/transition" class="actions">@csrf<input type="hidden" name="_deliberate" value="1"><input type="hidden" name="revision" value="{{ old('revision',$row->revision) }}">@if($manager && $row->status==='Requested')<button name="action" value="return">Return to Draft</button>@endif @if($row->status==='Draft' && ($manager || (int)$row->owner_id===(int)auth()->id()))<button class="discard" name="action" value="cancel" data-confirm="Cancel this Draft? All saved details and activity will be retained.">Cancel request</button>@endif</form>
<form method="post" action="/relocations/{{ $row->id }}/copy" class="actions">@csrf<input type="hidden" name="_deliberate" value="1"><button>Copy items to new Draft</button></form><p>Shipment and receipt posting are unavailable until their workflows are delivered.</p>
@include('requests.activity')<script src="/requests.js" defer></script>
@endsection
