@extends('layout')
@section('title', $row ? 'Edit Relocation Request' : 'New Relocation Request')
@section('content')
<p>Title, Source and Destination are required to save a Draft. Items can wait until review. Quantities are individual units. No stock is reserved.</p>
@if(!$draft['source_location_id'])<p class="warning">Choose an active Source before saving. New requests default to the designated active Central location when available; ask a catalog manager if Central is missing or ineligible. Existing incomplete Drafts require valid choices on their next save.</p>@endif
<form method="post" action="/relocations/work/{{ $token }}" data-request-form>@csrf<input type="hidden" name="_deliberate" value="1">
<label>Title<input name="title" required maxlength="255" value="{{ old('title',$draft['title']) }}"></label>
<div class="app-relocation-locations"><label>Source<select name="source_location_id" required>@if(!old('source_location_id',$draft['source_location_id']))<option value="" disabled selected>Choose an active Source</option>@endif @foreach($locations as $location)@if($location->state==='active' || (string)$location->id===(string)$draft['source_location_id'])<option value="{{ $location->id }}" @selected((string)old('source_location_id',$draft['source_location_id'])===(string)$location->id)>{{ $location->name }}@if($location->state !== 'active') ({{ $location->state }})@endif</option>@endif
@endforeach</select></label>
<span class="app-location-arrow" aria-hidden="true">→</span><label>Destination<select name="destination_location_id" required><option value="">Choose a Destination</option>@foreach($locations as $location)@if($location->state==='active' || (string)$location->id===(string)$draft['destination_location_id'])<option value="{{ $location->id }}" @selected((string)old('destination_location_id',$draft['destination_location_id'])===(string)$location->id)>{{ $location->name }}@if($location->state !== 'active') ({{ $location->state }})@endif</option>@endif
@endforeach</select></label>
</div>
<label class="app-relocation-notes">Notes (optional)<textarea name="details" maxlength="5000">{{ old('details',$draft['details']) }}</textarea></label>
<section class="requested-items"><h2>Requested Items</h2><p>Projections use current balances and requested units; they do not reserve stock. Change locations then use Search or Save to refresh current balances.</p><x-app.table-region label="Relocation items" class="table-wrap"><table class="stock-editor"><thead><tr><th>Item</th><th>Source: current → projected</th><th>Destination: current → projected</th><th>Request</th><th></th></tr></thead><tbody>@include('requests.relocation-rows',['quantities'=>old('lines',$draft['lines']),'editing'=>true,'columns'=>5])</tbody></table></x-app.table-region></section>
<div class="actions"><a class="discard" href="{{ $row ? '/relocations/'.$row->id : '/relocations' }}">Discard</a>@if(!$row || $row->status==='Draft')<button name="action" value="save">Save Draft</button><button name="action" value="review" class="primary">Review request</button>@else<button name="action" value="save" class="primary">Save request</button>@endif</div>
<h2>Add items</h2><div class="search-actions"><label>Search inventory<input name="search" maxlength="255" value="{{ old('search',$draft['criteria']['search'] ?? '') }}"></label><button name="action" value="search" formnovalidate>Search</button><button name="action" value="show_all" formnovalidate>Show All</button><button name="action" value="reset" formnovalidate>Reset</button></div>
<details><summary>Collection filters</summary><div class="collection-checklist">@foreach($collections as $collection)<label class="app-choice"><input type="checkbox" name="collections[]" value="{{ $collection->id }}" @checked(in_array($collection->id,old('collections',$draft['criteria']['collections'] ?? [])))>{{ $collection->category_name }} : {{ $collection->name }}</label>@endforeach</div></details>
@if($draft['criteria'] !== null)<p>Added items are excluded. Nonblank nonnumeric entries add zero; negative, fractional or excessive numbers are rejected.</p><div class="actions"><button name="action" value="add" formnovalidate>Add Selected</button></div><x-app.table-region label="Search results to add" class="table-wrap"><table class="stock-editor"><thead><tr><th>Item</th><th>Current source</th><th>Current destination</th><th>Request</th></tr></thead><tbody>@php($group=null)@forelse($results as $item)@if($group!==$item['category'].' : '.$item['collection'])@php($group=$item['category'].' : '.$item['collection'])<tr class="collection-heading"><th colspan="4">{{ $group }}</th></tr>@endif<tr><th>{{ $item['name'] }}</th><td class="number">{{ $item['source'] === null ? 'Unknown' : number_format($item['source']) }}</td><td class="number">{{ $item['destination'] === null ? 'Unknown' : number_format($item['destination']) }}</td><td><input name="selection[{{ $item['id'] }}]" aria-label="Add quantity for {{ $item['name'] }} (optional)" value="{{ old('selection.'.$item['id']) }}"></td></tr>@empty<tr><td colspan="4">No matching active items to add.</td></tr>@endforelse</tbody></table></x-app.table-region>@endif
</form><script src="/requests.js" defer></script>
@endsection
