@extends('layout')
@section('title', $row->title)
@section('title-status')<span class="status-badge request-status {{ strtolower($row->status) }}">{{ $row->status }}</span>@endsection
@section('content')
<p>Relocation #{{ $row->id }} · Owner: {{ trim($owner->first_name.' '.$owner->last_name) ?: 'Account '.$owner->id }}</p>
<div class="actions"><a href="/relocations">All relocation requests</a><a class="button" href="/relocations/{{ $row->id }}/worksheet" target="_blank" rel="noopener">Packing worksheet</a>@if($editable)<a class="button" href="/relocations/{{ $row->id }}/edit">{{ $row->status==='Draft' ? 'Edit Draft' : 'Edit request' }}</a>@endif</div>
<p>{{ $locations->firstWhere('id',$row->source_location_id)?->name ?: 'Source not selected' }} → {{ $locations->firstWhere('id',$row->destination_location_id)?->name ?: 'Destination not selected' }}</p><p class="plain-text">{{ $row->details }}</p>
@if($manager || (int)$row->owner_id === (int)auth()->id())<details><summary>Edit title</summary><form method="post" action="/relocations/{{ $row->id }}/title" data-request-form>@csrf<input type="hidden" name="_deliberate" value="1"><input type="hidden" name="revision" value="{{ old('revision',$row->revision) }}"><label>Title<input name="title" maxlength="255" value="{{ old('title',$row->title) }}" required></label><button>Save title</button></form></details>@endif
<h2>Requested Items</h2><p>Projections use current inventory and reserve nothing. Saved counts move no stock.</p>
<form method="post" action="/relocations/{{ $row->id }}/fulfillment" data-request-form>@csrf<input type="hidden" name="_deliberate" value="1"><input type="hidden" name="revision" value="{{ old('revision',$row->revision) }}"><x-app.table-region label="Requested items and fulfillment" class="table-wrap"><table class="stock-editor"><thead><tr><th>Item</th><th>Source: current → projected</th><th>Destination: current → projected</th><th>Requested</th><th>Fulfillment preparation (optional)</th></tr></thead><tbody>@include('requests.relocation-rows',['quantities'=>$lines->map(fn($line)=>$line->quantity)->all(),'fulfillment'=>true,'columns'=>5])</tbody></table></x-app.table-region>@if($manager && $row->status==='Requested')<div class="actions"><button>Save fulfillment preparation</button></div>@endif</form>
<form method="post" action="/relocations/{{ $row->id }}/transition" class="actions">@csrf<input type="hidden" name="_deliberate" value="1"><input type="hidden" name="revision" value="{{ old('revision',$row->revision) }}">@if($manager && $row->status==='Requested')<button name="action" value="return">Return to Draft</button>@endif @if($row->status==='Draft' && ($manager || (int)$row->owner_id===(int)auth()->id()))<button class="discard" name="action" value="cancel" data-confirm="Cancel this Draft? All saved details and activity will be retained.">Cancel request</button>@endif</form>
<form method="post" action="/relocations/{{ $row->id }}/copy" class="actions">@csrf<input type="hidden" name="_deliberate" value="1"><button>Copy items to new Draft</button></form>
@if($fulfillmentReady)
<div class="actions">@if($manager && $row->status==='Requested')<a class="button primary" href="/relocations/{{ $row->id }}/fulfillment/shipment">Record shipment</a>@endif
@if(in_array($row->status,['Shipped','Receiving']) && ($manager || (int)$row->owner_id===(int)auth()->id()))<a class="button primary" href="/relocations/{{ $row->id }}/fulfillment/receipt">Receive shipment</a>@endif
@if(in_array($row->status,['Shipped','Receiving','Complete']))<a class="button" href="/relocations/{{ $row->id }}/fulfillment/shipment?view=1">View sent quantities</a><a class="button" href="/relocations/{{ $row->id }}/fulfillment/receipt?view=1">View received quantities</a>@endif</div>
<h2>Shipping information</h2><p>Shipped date: {{ !empty($shipment['shipped_date']) ? \App\Support\DisplayDates::businessDate($shipment['shipped_date']) : '—' }} · Received date: {{ !empty($shipment['received_date']) ? \App\Support\DisplayDates::businessDate($shipment['received_date']) : '—' }}</p>
<ul>@foreach($shipment['tracking'] as $track)@php($url=\App\Support\RelocationFulfillment::trackingUrl($track))<li>{{ $track['carrier'] }}: @if($url)<a href="{{ $url }}" target="_blank" rel="noopener">{{ $track['number'] }}</a>@else{{ $track['number'] }}@endif</li>@endforeach</ul>
@if($manager && in_array($row->status,['Requested','Shipped','Receiving','Complete']))<details><summary>Edit tracking</summary><form method="post" action="/relocations/{{ $row->id }}/tracking" data-request-form>@csrf<input type="hidden" name="_deliberate" value="1"><input type="hidden" name="revision" value="{{ $row->revision }}">
@foreach(array_merge($shipment['tracking'],[['carrier'=>'Other','number'=>'','url'=>''],['carrier'=>'Other','number'=>'','url'=>'']]) as $index=>$track)<fieldset><legend>Tracking line {{ $index+1 }}</legend><label>Carrier<select name="tracking[{{ $index }}][carrier]">@foreach(['USPS','UPS','FedEx','DHL','Other'] as $carrier)<option @selected($track['carrier']===$carrier)>{{ $carrier }}</option>@endforeach</select></label><label>Tracking number (optional)<input name="tracking[{{ $index }}][number]" value="{{ old('tracking.'.$index.'.number',$track['number']) }}" maxlength="255"></label><label>Other HTTPS link (optional)<input name="tracking[{{ $index }}][url]" value="{{ old('tracking.'.$index.'.url',$track['url']) }}" type="url" maxlength="255"></label></fieldset>@endforeach<button>Save tracking</button></form></details>@endif
@else<p>Shipment and receipt posting need guarded fulfillment preparation.</p>@endif
@include('requests.activity')<script src="/requests.js" defer></script>
@endsection
