@extends('layout')
@section('title', $row ? 'Edit Relocation Request' : 'New Relocation Request')
@section('content')
<p>Required title; locations and items can wait until review. Quantities are individual units. No stock is reserved.</p>
<form method="post" action="/relocations/work/{{ $token }}" data-request-form>@csrf<input type="hidden" name="_deliberate" value="1">
<label>Title<input name="title" maxlength="255" value="{{ old('title',$draft['title']) }}"></label>
<label>Source storage<select name="source_location_id"><option value="">Not selected</option>@foreach($locations as $location)@if($location->state==='active' || (string)$location->id===(string)$draft['source_location_id'])<option value="{{ $location->id }}" @selected((string)old('source_location_id',$draft['source_location_id'])===(string)$location->id)>{{ $location->name }} ({{ $location->state }})</option>@endif
@endforeach</select></label>
<label>Destination storage<select name="destination_location_id"><option value="">Not selected</option>@foreach($locations as $location)@if($location->state==='active' || (string)$location->id===(string)$draft['destination_location_id'])<option value="{{ $location->id }}" @selected((string)old('destination_location_id',$draft['destination_location_id'])===(string)$location->id)>{{ $location->name }} ({{ $location->state }})</option>@endif
@endforeach</select></label>
<label>Request details<textarea name="details" maxlength="5000">{{ old('details',$draft['details']) }}</textarea></label>
<section class="requested-items"><h2>Requested Items</h2><p>Projections use current balances and requested units; they do not reserve stock. Change locations then use Search or Save to refresh current balances.</p><div class="table-wrap"><table class="stock-editor"><thead><tr><th>Item</th><th>Source: current → projected</th><th>Destination: current → projected</th><th>Request</th><th></th></tr></thead><tbody>@include('requests.relocation-rows',['quantities'=>old('lines',$draft['lines']),'editing'=>true,'columns'=>5])</tbody></table></div></section>
<div class="actions"><a class="discard" href="{{ $row ? '/relocations/'.$row->id : '/relocations' }}">Discard</a>@if(!$row || $row->status==='Draft')<button name="action" value="save">Save Draft</button><button name="action" value="review" class="primary">Review request</button>@else<button name="action" value="save" class="primary">Save request</button>@endif</div>
<h2>Add items</h2><div class="search-actions"><label>Search inventory<input name="search" maxlength="255" value="{{ old('search',$draft['criteria']['search'] ?? '') }}"></label><button name="action" value="search">Search</button><button name="action" value="show_all">Show All</button><button name="action" value="reset">Reset</button></div>
<details><summary>Collection filters</summary><div class="collection-checklist">@foreach($collections as $collection)<label class="checkbox"><input type="checkbox" name="collections[]" value="{{ $collection->id }}" @checked(in_array($collection->id,old('collections',$draft['criteria']['collections'] ?? [])))>{{ $collection->category_name }} : {{ $collection->name }}</label>@endforeach</div></details>
@if($draft['criteria'] !== null)<p>Added items are excluded. Nonblank nonnumeric entries add zero; negative, fractional or excessive numbers are rejected.</p><div class="actions"><button name="action" value="add">Add Selected</button></div><div class="table-wrap"><table class="stock-editor"><thead><tr><th>Item</th><th>Current source</th><th>Current destination</th><th>Request</th></tr></thead><tbody>@php($group=null)@forelse($results as $item)@if($group!==$item['category'].' : '.$item['collection'])@php($group=$item['category'].' : '.$item['collection'])<tr class="collection-heading"><th colspan="4">{{ $group }}</th></tr>@endif<tr><th>{{ $item['name'] }}</th><td class="number">{{ number_format($item['source']) }}</td><td class="number">{{ number_format($item['destination']) }}</td><td><input name="selection[{{ $item['id'] }}]" aria-label="Add quantity for {{ $item['name'] }}" value="{{ old('selection.'.$item['id']) }}"></td></tr>@empty<tr><td colspan="4">No matching active items to add.</td></tr>@endforelse</tbody></table></div>@endif
</form><script src="/requests.js" defer></script>
@endsection
